---
# Source: try/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      web: app
  template:
    metadata:
      labels:
        web: app
    spec:
      containers:
      - name: test
        image: "00vinay/hi:latest"
        ports:
        - containerPort: 80
